name: doctr_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - python-doctr==0.10.0
      - onnxruntime==1.19.2
      - onnx==1.18.0
      - opencv-python==4.11.0.86
      - PyMuPDF==1.26.1
      - pdf2image==1.17.0
      - pytesseract==0.3.13
      - numpy==2.0.2
      - pandas==2.3.0
      - scikit-learn==1.6.1
      - pillow==11.2.1
      - scikit-image==0.24.0
      - torch==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - pypdfium2==4.30.1
      - PyYAML==6.0.2
      - openpyxl==3.1.5
